name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Enable Flutter Web
        run: flutter config --enable-web
      - name: Install dependencies
        run: flutter pub get
      - name: Build Web
        run: flutter build web --base-href "/devfolio/"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web